### ISSUE TITLE
sekrit.php

### ISSUE THREAD

**Issue by AntoineLange** [TheTree/Leaf#15]
Hi,
Great app, i like the windows 8 like interface.
I'm new with CI, and Github, and i would make a little app for the french halo community, so i try you app but i have the error that i need the skrit file ( to get the Spartant Auth i think)
Can we have the sekrit.php file please ?

Thanks

**Comment by iBotPeaches** [comment]
You have to figure that part on your own :)

I'm not giving out the entire source code to Leaf, otherwise people could install it anywhere and just take my work. All the information required to do that is on the web.

**Comment by AntoineLange** [comment]
Ok I understand.
I follow all the auntiedotnet wiki documentation, but oAuth is new for me and i can't find french docs so it's hard sometimes.
It has been 3 days since i'm looking for how to get the Spartan Auth Key. I already get this only if i take the WLID acces token from the halowaypoint application and send the GET HTTP request to https://settings.svc.halowaypoint.com/RegisterClientService.svc/spartantoken/wlid with the good header (X-343-Authorization-WLID: : [OAUTH_ACCESS_TOKEN]), but i don't succeed to get the right WLID access token.

Could you point me to the right way please ?

Thanks.

**Comment by 0xdeafcafe** [comment]
Everything you need to help you understand how to do it is all on the AuntieDot Wiki (http://api.auntiedot.net/index.php?title=Main_Page)

**Comment by AntoineLange** [comment]
Ok last question please,

Do you get the WLID access using the Live Connect OAuth with a POST request to https://login.live.com/oauth20_token.srf or do you recover the WLID access token from the halowaypoint app with a regex or something else ?

Sorry but this is this sentence "However, don't fret, you can just do the oauth process programmatically and scrape the access_token, authentication_token, and expires_in from the html" that i don't understand and so, i can't get the right WLID token.

Regards.
