### ISSUE TITLE
News 2.0

### ISSUE THREAD

**Issue by iBotPeaches** [TheTree/Leaf#26]
If Leaf is gonna grow, our News system needs a serious update.
- [x] Use clean_seo name in url (ex title-id), instead of id
- [x] Allow use of bbcode in articles (bold, italic, images, lists, etc)
- [x] rel 'prev' and rel 'next' on pagination on news page
- [x] Comments via Discus
- [x] Comment count on home page
- [x] Remove targetted ad shit from Discus

**Comment by 0xdeafcafe** [comment]
I just use markdown for a BBCode system in blogs.

**Comment by iBotPeaches** [comment]
I just need bold and lists, markdown = overkill :p

**Comment by 0xdeafcafe** [comment]
It's so simple to add, at least it was in rails ;).
