### ISSUE TITLE
CSR ranks aren't displaying for my gamertag (Lightingstrike)

### ISSUE THREAD

**Issue by MuskratLod** [TheTree/Leaf#27]
After refreshing my page a couple times, the first CSR view look was non-existent. Could you correct this problem for me?

http://leafapp.co/gt/lightingstrike

**Comment by iBotPeaches** [comment]
How the hell did that happen. 

Yeah ill get on it.

**Comment by iBotPeaches** [comment]
The real bug, as I have yet to fix, but its fixed for now :)

If a profile goes inactive and comes back from in-activeness, the record in `ci_csr` is never returned back to 0. Thus, the record in `ci_players` has a Status of 0, compared to the Status of 3 on `ci_csr`.

Abstract `change_status` to a library function, so we can force Status change on both `ci_csr` and `ci_players`.
