### ISSUE TITLE
CSR mouseover

### ISSUE THREAD

**Issue by theoryyylol** [TheTree/Leaf#4]
Hey, Great web app. Love the interface, a quick suggestion though. When you look at your CSR ratings, currently It does not display the playlist until you mouseover. It would be awesome if it had the name of the playlist over the CSR rating.

thanks!

**Comment by iBotPeaches** [comment]
Yeah its a tooltip. Still haven't found the perfect "metro" friendly way to display the name without compromising the design.

**Comment by theoryyylol** [comment]
Ah, metro style. Hey it's still great and not a big problem by means. I will be telling everyone I know about it in the meantime!

Stephen Dougherty
Dumb Luck Productions
"Stay Hungry, Stay Foolish"

**Comment by iBotPeaches** [comment]
Fixed this w/ my new CSR layout.
